---
- name: Get Repository Information
  hosts: ise_servers
  vars_files:
    - credentials.yml
  gather_facts: false
  tasks:
    - name: Get all Repositories
      cisco.ise.repository_info:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
        ise_version: "{{ ise_version }}"
      register: result

    - name: Print Repositories
      ansible.builtin.debug:
        var: result.ise_response
    - name: Get Repository by name
      cisco.ise.repository_info:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
        name: backup-repo
      register: result_by_name

    - name: Print Repository by Name
      ansible.builtin.debug:
        var: result_by_name.ise_response
